import React from 'react';
import Layout from '@theme/Layout';
import styles from '@site/src/components/TemplatePage/styles.module.css';

export default function TemplatesIndex() {
  return (
    <Layout
      title="Free 3D World Templates | LocalGPT Gen"
      description="Discover free, AI-generated 3D world templates for your games and projects. Fantasy, Sci-Fi, Horror, and Urban environments ready to customize.">

      <div className={styles.hero}>
        <div className="container">
          <h1 className={styles.heroTitle}>3D World Templates</h1>
          <p className={styles.heroSubtitle}>
            Coming soon — ready-to-customize world templates generated by LocalGPT Gen.
          </p>
        </div>
      </div>

      <div className="container">
        <div style={{ padding: '4rem 0', textAlign: 'center' }}>
          <p style={{ fontSize: '1.1rem', opacity: 0.8 }}>
            Fantasy, Sci-Fi, Horror, and Urban environments — fully explorable, customizable, and free to use.
          </p>
          <p style={{ opacity: 0.6 }}>
            Templates are currently being developed. Check back soon!
          </p>
        </div>
      </div>
    </Layout>
  );
}
