import React from 'react';
import Layout from '@theme/Layout';
import Link from '@docusaurus/Link';
import { templates } from '@site/src/data/templates';
import styles from '@site/src/components/TemplatePage/styles.module.css';

export default function TemplatesIndex() {
  const categories = ['fantasy', 'sci-fi', 'horror', 'urban'] as const;

  return (
    <Layout
      title="Free 3D World Templates | LocalGPT Gen"
      description="Discover free, AI-generated 3D world templates for your games and projects. Fantasy, Sci-Fi, Horror, and Urban environments ready to customize.">
      
      <div className={styles.hero}>
        <div className="container">
          <h1 className={styles.heroTitle}>3D World Templates</h1>
          <p className={styles.heroSubtitle}>
            Jumpstart your project with production-ready environments generated by LocalGPT Gen.
            Fully explorable, customizable, and free to use.
          </p>
        </div>
      </div>

      <div className="container">
        <div style={{ padding: '4rem 0' }}>
            {categories.map(category => (
                <div key={category} style={{ marginBottom: '4rem' }}>
                    <div style={{display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1.5rem', borderBottom: '1px solid var(--ifm-color-emphasis-200)', paddingBottom: '0.5rem'}}>
                        <h2 style={{textTransform: 'capitalize', margin: 0}}>{category} Templates</h2>
                        <Link to={`/templates/${category}`} className="button button--outline button--primary button--sm">
                            View All {category}
                        </Link>
                    </div>
                    <div className={styles.relatedGrid}>
                        {templates.filter(t => t.category === category).slice(0, 3).map(t => (
                            <Link 
                                key={t.id} 
                                to={`/templates/${t.slug}`} 
                                className={styles.relatedCard}>
                                <h4>{t.title}</h4>
                                <p>{t.description}</p>
                            </Link>
                        ))}
                    </div>
                </div>
            ))}
        </div>
      </div>
    </Layout>
  );
}
